2018-08-16 11:25:00,373 INFO: Artemis Startup [in /home/nate/Documents/BadDoggy/Artemis/app/__init__.py:50]
2018-08-16 11:25:48,658 INFO: Artemis Startup [in /home/nate/Documents/BadDoggy/Artemis/app/__init__.py:50]
2018-08-16 11:26:53,195 INFO: Artemis Startup [in /home/nate/Documents/BadDoggy/Artemis/app/__init__.py:50]
2018-08-16 11:27:17,602 INFO: Artemis Startup [in /home/nate/Documents/BadDoggy/Artemis/app/__init__.py:50]
2018-08-16 11:27:30,572 INFO: Artemis Startup [in /home/nate/Documents/BadDoggy/Artemis/app/__init__.py:50]
2018-08-16 11:27:42,418 INFO: Artemis Startup [in /home/nate/Documents/BadDoggy/Artemis/app/__init__.py:50]
2018-08-16 11:28:10,569 INFO: Artemis Startup [in /home/nate/Documents/BadDoggy/Artemis/app/__init__.py:50]
2018-08-16 11:28:39,094 ERROR: Exception on / [GET] [in /home/nate/.local/lib/python3.6/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/home/nate/.local/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/nate/.local/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/nate/.local/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/nate/.local/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/nate/.local/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/nate/.local/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/nate/.local/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/nate/Documents/BadDoggy/Artemis/app/routes.py", line 39, in index
    prev_url=prev_url)
  File "/home/nate/.local/lib/python3.6/site-packages/flask/templating.py", line 135, in render_template
    context, ctx.app)
  File "/home/nate/.local/lib/python3.6/site-packages/flask/templating.py", line 117, in _render
    rv = template.render(context)
  File "/home/nate/.local/lib/python3.6/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/home/nate/.local/lib/python3.6/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/nate/.local/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/nate/.local/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/nate/Documents/BadDoggy/Artemis/app/templates/index.html", line 2, in top-level template code
    {% import 'bootstrap/wtf.html' as wtf %}
  File "/home/nate/Documents/BadDoggy/Artemis/app/templates/base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "/home/nate/.local/lib/python3.6/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 1, in top-level template code
    {% block doc -%}
  File "/home/nate/.local/lib/python3.6/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 4, in block "doc"
    {%- block html %}
  File "/home/nate/.local/lib/python3.6/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 20, in block "html"
    {% block body -%}
  File "/home/nate/.local/lib/python3.6/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 23, in block "body"
    {% block content -%}
  File "/home/nate/Documents/BadDoggy/Artemis/app/templates/base.html", line 48, in block "content"
    {% block app_content %}{% endblock %}
  File "/home/nate/Documents/BadDoggy/Artemis/app/templates/index.html", line 11, in block "app_content"
    {% include '_post.html' %}
  File "/home/nate/Documents/BadDoggy/Artemis/app/templates/_post.html", line 14, in top-level template code
    {{ _('%(username)s said %(when)s',
  File "/home/nate/.local/lib/python3.6/site-packages/jinja2/ext.py", line 134, in _gettext_alias
    return __context.call(__context.resolve('gettext'), *args, **kwargs)
TypeError: gettext() takes 2 positional arguments but 3 were given
2018-08-16 11:29:35,318 INFO: Artemis Startup [in /home/nate/Documents/BadDoggy/Artemis/app/__init__.py:50]
2018-08-16 11:29:43,229 INFO: Artemis Startup [in /home/nate/Documents/BadDoggy/Artemis/app/__init__.py:50]
2018-08-16 11:29:48,601 ERROR: Exception on /index [GET] [in /home/nate/.local/lib/python3.6/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/home/nate/.local/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/nate/.local/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/nate/.local/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/nate/.local/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/nate/.local/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/nate/.local/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/nate/.local/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/nate/Documents/BadDoggy/Artemis/app/routes.py", line 39, in index
    prev_url=prev_url)
  File "/home/nate/.local/lib/python3.6/site-packages/flask/templating.py", line 135, in render_template
    context, ctx.app)
  File "/home/nate/.local/lib/python3.6/site-packages/flask/templating.py", line 117, in _render
    rv = template.render(context)
  File "/home/nate/.local/lib/python3.6/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/home/nate/.local/lib/python3.6/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/nate/.local/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/nate/.local/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/nate/Documents/BadDoggy/Artemis/app/templates/index.html", line 2, in top-level template code
    {% import 'bootstrap/wtf.html' as wtf %}
  File "/home/nate/Documents/BadDoggy/Artemis/app/templates/base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "/home/nate/.local/lib/python3.6/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 1, in top-level template code
    {% block doc -%}
  File "/home/nate/.local/lib/python3.6/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 4, in block "doc"
    {%- block html %}
  File "/home/nate/.local/lib/python3.6/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 20, in block "html"
    {% block body -%}
  File "/home/nate/.local/lib/python3.6/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 23, in block "body"
    {% block content -%}
  File "/home/nate/Documents/BadDoggy/Artemis/app/templates/base.html", line 48, in block "content"
    {% block app_content %}{% endblock %}
  File "/home/nate/Documents/BadDoggy/Artemis/app/templates/index.html", line 11, in block "app_content"
    {% include '_post.html' %}
  File "/home/nate/Documents/BadDoggy/Artemis/app/templates/_post.html", line 14, in top-level template code
    {{ _('%(username)s said %(when)s',
  File "/home/nate/.local/lib/python3.6/site-packages/jinja2/ext.py", line 134, in _gettext_alias
    return __context.call(__context.resolve('gettext'), *args, **kwargs)
TypeError: gettext() takes 2 positional arguments but 3 were given
2018-08-16 12:39:18,034 INFO: Artemis Startup [in /home/nate/Documents/BadDoggy/Artemis/app/__init__.py:50]
2018-08-16 12:40:03,984 INFO: Artemis Startup [in /home/nate/Documents/BadDoggy/Artemis/app/__init__.py:50]
2018-08-16 12:40:48,067 INFO: Artemis Startup [in /home/nate/Documents/BadDoggy/Artemis/app/__init__.py:50]
2018-08-16 12:41:13,082 INFO: Artemis Startup [in /home/nate/Documents/BadDoggy/Artemis/app/__init__.py:50]
2018-08-16 12:41:19,642 INFO: Artemis Startup [in /home/nate/Documents/BadDoggy/Artemis/app/__init__.py:50]
2018-08-20 14:42:02,911 INFO: Artemis Startup [in /home/nate/Documents/BadDoggy/Artemis/app/__init__.py:50]
2018-08-20 14:42:47,099 ERROR: Exception on /unfollow/Sunflower [GET] [in /home/nate/.local/lib/python3.6/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/home/nate/.local/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/nate/.local/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/nate/.local/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/nate/.local/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/nate/.local/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/nate/.local/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/nate/.local/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/nate/Documents/BadDoggy/Artemis/app/routes.py", line 148, in unfollow
    db.session.commt()
AttributeError: 'scoped_session' object has no attribute 'commt'
